language: node_js

services:
  - couchdb

node_js:
  - "0.12"

addons:
  firefox: "latest"

script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

env:
  matrix:
  - CLIENT=selenium:firefox GREP=suite2 INVERT=true COMMAND=test
  - CLIENT=selenium:firefox GREP=suite2 COMMAND=test

branches:
  only:
  - master
  - /^pull*$/
