language: node_js

services:
  - couchdb

node_js:
  - "0.12"

addons:
  firefox: "latest"

script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

env:
  matrix:
  # break into many small tests so travis doesn't complain
  - CLIENT=selenium:firefox SUITE=1 COMMAND=test
  - CLIENT=selenium:firefox SUITE=2 COMMAND=test
  - CLIENT=selenium:firefox SUITE=3 COMMAND=test
  - CLIENT=selenium:firefox SUITE=4 COMMAND=test

branches:
  only:
  - master
  - /^pull*$/
